### ISSUE TITLE
What does our marketing funnel look like?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/data-ops#21]
I'd love to have a good view into what our marketing funnel looks like.  Here are the steps I imagine:

FUNDER
* Visitor to funder landing page
* Clicks 'sign up'
* Actually Signs up
* Funds an issue
* Completes an issue

CONTRIBUTOR
* Contributor goes to contributor LP
* Clicks 'sign up'
* Actually Signs up
* Starts work on an issue
* Completes an issue

**Comment by frankchen07** [comment]
Dug into this a little bit after getting HotJar access and found some issues with tracking funder FTUX, and have some suggestions for improvement. 

---

> Funder FTUX

The flow as it currently stands in HotJar:

https://gitcoin.co/onboard/funder/github
https://gitcoin.co/onboard/funder/metamask
https://gitcoin.co/onboard/funder/avatar

Couple of issues exist:

https://gitcoin.co/onboard/funder/github is a dead link. The link should be https://gitcoin.co/onboard/funder/. However, after some searching around gitcoin.co, I don't see a way for an unregistered or registered user to land on `/onboard/funder` except by directly typing the URL into the address bar. This may be the reason why the funnel is broken (not showing any data in HotJar), and that tells me there isn't really an intuitive funder FTUX flow. 

<img width="1678" alt="screen shot 2018-09-26 at 15 23 28" src="https://user-images.githubusercontent.com/7516920/46125956-29a03380-c1e0-11e8-9e61-ad81c5f2a4c9.png">

Issue logged here: https://github.com/gitcoinco/web/issues/2282

Once we have that fixed, I'd like to separate the funnel analysis into two portions: an acquisition funnel and a "funded an issue" funnel, since those are two somewhat separate actions. That being said, it's not difficult to create one combined funnel (we can still do that), but I still think seeing the separate actions by splitting the funnel up will still be useful.

---

I'm able to hit "Fund Issue" and get to `funding/new` with Metamask enabled and _without signing in_. If this is allowed, which I don't think it should be, a new user essentially bypasses any kind of FTUX before getting to the funding page. This might be confusing. 

<img width="1679" alt="screen shot 2018-09-26 at 15 03 55" src="https://user-images.githubusercontent.com/7516920/46126052-9b787d00-c1e0-11e8-97ce-9a6d569030ad.png">

Bug logged here: https://github.com/gitcoinco/web/issues/2284

---

> Contributor FTUX

The flow as it currently stands in HotJar: 

https://gitcoin.co/onboard/contributor/
https://gitcoin.co/onboard/contributor/metamask
https://gitcoin.co/onboard/contributor/avatar
https://gitcoin.co/onboard/contributor/skills

This flow is fine, and currently exists in HotJar. Similar to the Funder FTUX, I'd like to split the funnel analysis into an acquisition and "contributed" funnel. The link getting to `onboard/contributor` is not obvious either (below, "Get Started with Gitcoin")

<img width="533" alt="screen shot 2018-09-26 at 15 49 54" src="https://user-images.githubusercontent.com/7516920/46126164-01fd9b00-c1e1-11e8-88cb-f20eb516beb7.png">

I've similarly suggested that we make an obvious CTA on the homepage for the contributor FTUX: https://github.com/gitcoinco/web/issues/2283

---

### FTUX Suggestions and Thoughts

I think we should tidy up our FTUX flows and make it so there's only 1-2 obvious ways to get dropped into the funnel. Two methods I see:

Method 1: An unregistered user is a contributor and gets dropped into `/onboard/contributor`, or the unregistered user is a funder and gets dropped into `/onboard/funder`. All funder/contributor onboarding-specific CTAs throughout gitcoin.co should deposit the user at the appropriate landing page, starting with more obvious CTAs on the homepage.

Method 2: An unregistered user who clicks on "Log In" in the top right hand corner and connects their Github to Gitcoin will be dropped into the onboarding flow, at the Metamask step. However, if a user proceeds through this step, an open question is **how do we know if they're a funder or contributor, and how do we know which onboarding flow to drop them into?** (this begs the question if we can combine the funder and contributor FTUX into one funnel that branches off based on a simple "funder or contributor?" multiple choice question).

**Comment by owocki** [comment]
thanks for the thoughtful response Frank.. 

Hopefully those 404s are an easy fix.

> Method 1:

I'm a big fan of method 1.

**Comment by mbeacom** [comment]
`https://gitcoin.co/onboard/funder/github` isn't quite a dead link, we just don't allow direct access to either `https://gitcoin.co/onboard/funder/github`, `https://gitcoin.co/onboard/funder/metamask`, or `https://gitcoin.co/onboard/funder/avatar` directly.  Where is `https://gitcoin.co/onboard/funder/github` being referenced directly? `https://gitcoin.co/onboard/funder/` should be the tracked URL though 👍

**Comment by frankchen07** [comment]
Ah @mbeacom - that's good to know. Thanks!

`https://gitcoin.co/onboard/funder/github` was one of the tracked links in our funder FTUX in HotJar - which hypothetically should be interchangeable with `https://gitcoin.co/onboard/funder/` (please tell me if this is not the case). 

^ This doesn't quite fix our funder FTUX funnel just yet, since there isn't a clickable link that drops a user onto `/onboard/funder` (it is indeed a tracked URL, but I don't see a way to get there. Where does one click?). I wanted to make sure that's the case, and if so, I want to set up bounties for:

1. https://github.com/gitcoinco/web/issues/2282
2. https://github.com/gitcoinco/web/issues/2283
