### ISSUE TITLE
operational excellence / issue explorer questions, resultant from looking at data dashboards

### ISSUE THREAD

**Issue by owocki** [gitcoinco/data-ops#5]
- [x] 1. why is the [bounty throughput down](http://bits.owocki.com/3S1A022h3q1V/Screen%20Shot%202018-07-30%20at%201.18.41%20PM.png) ?
- [x] 2. why are there so many abandoned bounties?
- [x] 3. why are there so many stale bounties?
- [x] 4. 72% of our funders [are stale](http://bits.owocki.com/0Q0A3Y3E3H0R/Screen%20Shot%202018-07-30%20at%201.20.01%20PM.png). Why? How do we get them back?
- [x] 5. there are 4% of bounties that are 'at risk'. how do we intervene to make sure they are tackled?

**Comment by frankchen07** [comment]
@owocki 

> Why is bounty throughput down?

I might have not made it very clear. My original thought was to put "done" bounties as negative (to denote the count of bounties going down). Thinking about it now, it doesn't make it intuitive or comparable to other types of bounties. To take a better look, I've added a [comparison](https://metabase.gitcoin.co/question/75) on throughput rates week over week, based on open and done bounties, and the rate of bounties getting done is on average, higher for every week. There's some spikes and troughs, but nothing out of the ordinary. Switching the other throughput graphs to positive for done bounties makes the overall graph a little harder to read, but perhaps this is a consideration for later.

> Why so many abandoned and stale bounties?

Thanks for the catch. I've looked at the logic again and did some spot checking of github issues, and forgot that there can be bounties labeled as open with a fulfillment_started date. It would be interesting to see further iterations get really detailed with the "last github comment" data we have. For now, the logic stands as so:

```sql
case 
    when bi2.idx_status = 'done' then 'done'
    when bi2.idx_status = 'submitted' then 'submitted'
    when bi2.idx_status = 'cancelled' then 'cancelled'
    when bi2.idx_status = 'expired' then 'expired'
    when (bi2.idx_status = 'started' and now()::date - bi2.fulfillment_started_on::date > 14) then 'abandoned'
    when (bi2.idx_status = 'open' and now()::date - bi2.fulfillment_started_on::date > 14) then 'abandoned' 
    when (bi2.idx_status = 'started' and now()::date - bi2.fulfillment_started_on::date < 10) then 'in progress'
    when (bi2.idx_status = 'open' and now()::date - bi2.fulfillment_started_on::date < 10) then 'in progress' 
    when (bi2.idx_status = 'started' and now()::date - bi2.fulfillment_started_on::date between 10 and 14) then 'at risk'
    when (bi2.idx_status = 'open' and now()::date - bi2.fulfillment_started_on::date between 10 and 14) then 'at risk' 
    when (bi2.idx_status = 'open' and now()::date - bi2.created_on::date > 14 and bi2.fulfillment_started_on is null) then 'stale'
    when (bi2.idx_status = 'open' and now()::date - bi2.created_on::date <= 14 and bi2.fulfillment_started_on is null) then 'open'
end meta_category
```

Happy to add logic if anything is missing. This slightly modifies the rates.

> How to get stale funders back?

The basic logic comes down to if a funder hasn't posted a bounty in the past 30 days, from their most current funded bounty. A quick analysis [here](https://metabase.gitcoin.co/question/77) to see the relative distributions between stale and active funders shows us that the distribution looks relatively similar between stale and active funders, with active funders having a greater number of issues opened (which makes sense). I also created [a view](https://metabase.gitcoin.co/question/76) to see the last issue that an active or stale funder had opened, but it doesn't really give us any insight as to why they might have stopped.

How do we get them back? This is where I start thinking incentives. 

1. Part of it is growing Gitcoin so that it's a household name where funders know they will find quality people to help them out with their work. 
2. In the meantime, email touch points like we're doing now is an option (and underway). 
3. Could offering some kind of seed or re-seed amount of money to help them fund a couple of issues be possible? (I know we already have the faucet). 
4. We could just "do things that don't scale", and reach out to them individually. 
5. From data product perspective, we don't have any funnel analyses to figure out where people are dropping off in the funder flow. Is there some point where there's alot of friction?

Additional check on number 4: according to the funder flow, the bounty owner = funder, correct? Or can it be the case that the owner != funder sometimes?

> Dealing with at-risk bounties

New metric lowers the at-risk rate to about 0.5%. I would say that the issue explorer check-ins and Gitcoin bot are the main drivers of ensuring that at-risk bounties either move to a started stage, or, because the "at-risk" meta status is transient, it would eventually move to abandoned given enough time. We could do something similar to Vivek's issue explorer checkins - following up would be a viable way to check in. I'm actually slated to try this out for a couple of hours today, 8/9, or this coming weekend to kick off product work.

**Comment by owocki** [comment]
@ceresstation @vs77bb has the 'abandoned bounty' part of the opex dashboard been useful to you?

many funders have not been responding to the 'funder stale' emails unfortunately.. i think we may need to brainstorm better ways to get funders to return

> Additional check on number 4: according to the funder flow, the bounty owner = funder, correct? Or can it be the case that the owner != funder sometimes?

yes, we use them interchangeably

> From data product perspective, we don't have any funnel analyses to figure out where people are dropping off in the funder flow. Is there some point where there's alot of friction?

@frankchen07 
i'm very very very interested in figuring this out.  could we build a funnel in google analytics for this?
steps:
1. goes to funder form
2. dismisses metamask / 'how to do this model'
3. inserts github url
4. submits form
5. submits metamask tx
6. bounty is posted

**Comment by frankchen07** [comment]
@owocki - yeah I can open an issue and take a look in GA and tinker, we'll need some data points to understand how and why they're dropping off to determine if it's part of the flow that's causing it, or if it's something else.

+1 for comments on the 'abandoned bounty' part of the dash - if there is a way for it be more useful, I'm open to suggestions.
